homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 52.22967560
  longitude: 21.01222870
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 175
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw

# Enables the frontend
frontend:

#http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
# Checks for available updates
updater:
# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
logbook:
# Text to speech
tts:
  platform: google

mqtt:
  broker: 127.0.0.1

logger:
  default: debug

sensor command_sensor:
  - platform: mqtt
    name: target_thermostat_temperature
    state_topic: "home-assistant/lukasz/thermostat_settings"
    value_template: '{{ value_json.temperature}}'
    unit_of_measurement: "°C"

sensor command_sensor_2:
  - platform: mqtt
    name: target_thermostat_tolerance
    state_topic: "home-assistant/lukasz/thermostat_settings"
    value_template: '{{ value_json.tolerance }}'
    unit_of_measurement: "°C"

sensor command_sensor_3:
  - platform: command_line
    name: current_temperature
    command: "cat ~/.homeassistant/sensor_temperature.txt"
    unit_of_measurement: "°C"

climate:
  - platform: generic_thermostat
    name: Study
    heater: switch.study_heater
    operation_mode: auto
    target_sensor: sensor.current_temperature
    target_temperature: 15    

automation set_temp:
  trigger:
    platform: state
    entity_id: sensor.target_thermostat_temperature
  action:
    service: climate.set_temperature
    data_template:
      temperature: '{{ states.sensor.target_thermostat_temperature.state }}'

automation set_tol:
  trigger:
    platform: state
    entity_id: sensor.target_thermostat_tolerance
  action:
    service: climate.generic_thermostat_set_tolerance
    data_template:
      tolerance: '{{ states.sensor.target_thermostat_tolerance.state }}'

# # Track the sun
# sun:

device_tracker:
 - platform: nmap_tracker
   hosts: 192.168.0.1-40


